Repository CMU-313/spring23-nodebb-team-hecl-io, pull requests merged in 2023-04, with the labels that each got.

#95 Career model integration setup
  install/package.json
  node_modules/resolve/test/resolver/malformed_package_json/package.json
  package.json
  public/openapi/write.yaml
  public/openapi/write/career/register.yaml
  public/src/client/career.js
  public/src/modules/helpers.common.js
  src/controllers/authentication.js
  src/controllers/career.js
  src/controllers/index.js
  src/controllers/write/career.js
  src/controllers/write/index.js
  src/routes/write/career.js
  src/routes/write/index.js
  src/user/career.js
  src/user/index.js
  themes/nodebb-theme-persona/less/career.less
  themes/nodebb-theme-persona/templates/career.tpl
  themes/nodebb-theme-persona/templates/partials/career/recruiter.tpl
  themes/nodebb-theme-persona/templates/partials/career/student.tpl
Labels: bug, enhancement

#98 Fixed career page recruiter and student list bugs
  src/controllers/index.js
  src/user/create.js
Labels: bug

#104 bug fixes in predict.py and clean up main.py
  microservices/career-ml-service/main.py
  microservices/career-ml-service/predict.py
Labels: bug

#106 Re-added CD for pull requests
  .github/workflows/fly.yml
Labels: enhancement

#107 Update career.js
  src/controllers/write/career.js
Labels: enhancement

#109 Deployment fixes
  public/openapi/write.yaml
  public/openapi/write/career.yaml
Labels: bug

#111 Revert "Deployment fixes"
  public/openapi/write.yaml
  public/openapi/write/career.yaml
Labels: bug
