Repository CMU-313/spring23-nodebb-team-hecl-io, pull requests merged in 2023-03, with the labels that each got.

#61 Translated src/controllers/write/topics.js to Typescript
  src/controllers/write/topics.js
  src/controllers/write/topics.ts
Labels: enhancement

#63 Translated public/src/client/topic/events.js to Typescript
  public/src/client/topic/events.js
  public/src/client/topic/events.ts
Labels: enhancement

#65 Revert "Translated public/src/client/topic/events.js to Typescript"
  public/src/client/topic/events.js
  public/src/client/topic/events.ts
Labels: bug

#67 Resolves issue "(P10) Add endorsed and unendorse feature to topics and posts"
  public/openapi/write.yaml
  public/openapi/write/posts/pid/endorse.yaml
  public/src/client/topic/events.js
  public/src/client/topic/postTools.js
  src/api/helpers.js
  src/api/posts.js
  src/controllers/write/posts.js
  src/posts/delete.js
  src/posts/endorse.js
  src/posts/endorse.ts
  src/posts/index.js
  src/routes/write/posts.js
  src/topics/posts.js
  themes/nodebb-theme-persona/templates/partials/topic/post.tpl
Labels: documentation

#72 Revert "Fixed public/src/client/topic/events.ts translation"
  install/package.json
  public/src/client/topic/events.js
  public/src/client/topic/events.ts
  src/posts/endorse.js
  webpack.common.js
Labels: bug

#74 Bugfix making endorse button not change immidiately
  public/src/client/topic/events.js
  src/posts/endorse.js
Labels: bug

#77 Fixed endorse banner not changing until refresh
  public/src/client/topic/events.js
Labels: bug

#81 Unit tests for endorse feature
  test/posts.js
Labels: enhancement

#85 Deployed: Modified Dockerfile & connection.js. Added fly.toml file.
  Dockerfile
  fly.toml
  src/database/redis/connection.js
Labels: enhancement
